trigger:
- master

name: "Windows Release"

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseNode@1

  - script: npm install
    displayName: 'NPM Install'

  - script: npm pack
    displayName: "Packing up"

  - publish:  "*.tgz"
    displayName: "Publishing artifact"