trigger:
- master

name: "Windows Release"

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Build
    steps:
      - task: UseNode@1

      - script: npm install
        displayName: 'NPM Install'

      - pwsh: |
          mkdir ./artifacts
          cd ./artifacts
          npm pack ./../
        displayName: "Packing up"

      - publish: "./artifacts"
        displayName: "Publishing artifacts"
