trigger:
- master

name: "Windows Release"

pool:
  vmImage: 'windows-latest'

steps:

- task: UseNode@1

- script: npm install
  displayName: 'NPM Install'

- task: Npm@1
  inputs:
    command: 'publish'
    publishEndpoint: 'NPM JS'