trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseNode@1

- script: apt-get update && apt-get install libudev-dev
  displayName: "Setup Dependencies"

- script: npm install
  displayName: 'NPM Install'
